# Co-localization check of clusters and Jacobian

In [3]:
import pandas as pd
import numpy as np
import nibabel as nib

In [7]:
# Loading the Jacobian
img = nib.load('/data/bioprotean/SVD/colocalization/jac_tm_200pos_mask.nii')
jac = np.array(img.dataobj).flatten()
#jac = np.genfromtxt('/home/mabbasi6/morphometry/correlation/jac/csv/jac_masked.csv', delimiter=',').flatten()

In [34]:
df = pd.DataFrame(data=np.zeros((50,50)), index=[i for i in range(1,51)], columns=['cluster'+str(i) for i in range(1,51)])
df[:] = np.nan

In [35]:
df.head()

,cluster1,cluster2,cluster3,cluster4,cluster5,cluster6,cluster7,cluster8,cluster9,cluster10,...,cluster41,cluster42,cluster43,cluster44,cluster45,cluster46,cluster47,cluster48,cluster49,cluster50
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN