In [14]:
import numpy as np
import nibabel as nib
import os
import pandas as pd

In [15]:
img_jac = nib.load('/data/bioprotean/SVD/clusters/jac_tm_200pos_mask.nii')
data_jac = np.array(img_jac.dataobj)
flip = np.flip(data_jac, 2)
rotate = np.rot90(flip, k=1, axes=(1, 2))

In [16]:
# Counts the ratio of voxels over EACH CLUSTER
def count_func_label(labels, jacobian, n_clusters):
    # Defining the array that holds the ratios for each cluster
    count_arr = np.zeros(50)
    count_arr[:] = np.nan
    
    # Going through a loop for counting the ratio
    for k in range (n_clusters):
        labels_k = np.where(labels!=k, 0, 1)
        count_arr[k] = np.sum(labels_k * jacobian)/np.sum(labels_k)
    
    return count_arr

In [17]:
# Counts the ratio of voxels over WHOLE JACOBIAN
def count_func_jac(labels, jacobian, n_clusters):
    # Defining the array that holds the ratios for each cluster
    count_arr = np.zeros(50)
    count_arr[:] = np.nan
    
    # Going through a loop for counting the ratio
    for k in range (n_clusters):
        labels_k = np.where(labels!=k, 0, 1)
        count_arr[k] = np.sum(labels_k * jacobian)/np.sum(jacobian)
    
    return count_arr

In [ ]:
# testing the count function
a = np.array([1,2,2,2,2,3,3,0,0,0])
b = np.array([1,1,1,0,0,0,0,1,1,0])
count = count_func_label(a,b,4)
count

In [18]:
df = pd.DataFrame(data=np.zeros((50,50)), index=[i for i in range(1,51)], columns=['cluster'+str(i) for i in range(50)])
df[:] = np.nan

for i in range (1,51):
    img = nib.load('/data/bioprotean/SVD/clusters/nclusters_'+str(i)+'.nii')
    data_flat = np.array(img.dataobj).flatten()
    count_arr = count_func_jac(data_flat, rotate.flatten(), i)
    df.iloc[i-1] = count_arr[:]
df.to_csv('/data/bioprotean/SVD/colocalization/results_flip+rotated_jac.csv')

In [19]:
df.head()

,cluster0,cluster1,cluster2,cluster3,cluster4,cluster5,cluster6,cluster7,cluster8,cluster9,...,cluster40,cluster41,cluster42,cluster43,cluster44,cluster45,cluster46,cluster47,cluster48,cluster49
1,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.180536,0.819464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.074753,0.048895,0.876352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.045604,0.362953,0.552891,0.038552,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.045134,0.511989,0.273155,0.142924,0.026798,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN